name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.19.1
          cache: npm
      - run: npm ci
      - run: npm run lint:prettier
      - run: npm run lint:eslint
      - run: npm run lint:markuplint
